### ISSUE TITLE
مشکل این افزونه با یک پکیج لاراول

### ISSUE THREAD

**Issue by saeedvir** [amir9480/vscode-laravel-extra-intellisense#1]
پکیج زیر برای لاراول حالت ماژولار فراهم می کنه

`nwidart/laravel-modules`

به این صورت که مسیر های و کنترلر ها را به پوشه های مجزا منتقل می کنه
برای همین در اون بخش کار نمی کنه.
لطفا بررسی کنید.

اینم داکیومنت این پکیج
https://nwidart.com/laravel-modules/v4/introduction

**Comment by amir9480** [comment]
برای روت ها این افزونه مستقیما از دستور
`php artisan route:list`
استفاده میکنه و فقط کافیه روت توی این لیست تعریف شده باشه.
برای ویو هایی که 
namespace
دارن (مثل چیزی که این پکیج فراهم میکنه) هم مشکلشون رو برطرف کردم.
ممنون بابت گزارش.
![screenshot 25](https://user-images.githubusercontent.com/16279288/50918603-f06d9580-1455-11e9-8300-ca903879100c.png)

[0527938](https://github.com/amir9480/vscode-laravel-extra-intellisense/commit/887bb096ff2319ce613b767dd2b9e567c03e45bf)
