### ISSUE TITLE
php: not found

### ISSUE THREAD

**Issue by Temepest74** [amir9480/vscode-laravel-extra-intellisense#104]
I get this error whenever I open VSCode:
```
2024-04-15 10:29:11.776 [error] Laravel Extra Intellisense Error:
 HTTP Routes

/bin/sh: 1: php: not found
```
I am using sail to run my laravel app, and everything worked fine until I updated to the latest version.

**Comment by Temepest74** [comment]
Nvm, it looks like it happens frequently, not only when I open vscode. the full error code is:
```
2024-04-15 10:32:11.384 [info] Laravel Extra Intellisense command started: Application Models
2024-04-15 10:32:11.384 [info] Laravel Extra Intellisense command started: Auth Data
2024-04-15 10:32:11.403 [error] Laravel Extra Intellisense Error:
 Application Models

/bin/sh: 1: php: not found

2024-04-15 10:32:11.415 [error] Laravel Extra Intellisense Error:
 Auth Data

/bin/sh: 1: php: not found
```

**Comment by cubitworx** [comment]
I'm having the same problem starting with `v0.6.5`

If I install `v0.6.4` the problem goes away.

WSL2 on Windows with extension installed in WSL & project opened in WSL.

**Comment by serhumanos** [comment]
Same here in Linux KDE Neon (Ubuntu Based) v0.6.5 of the extension. no problem in v0.6.4

**Comment by branivreyes** [comment]
Same problem here` v0.6.5`, using docker containers.

**Comment by 1weiho** [comment]
![image](https://github.com/amir9480/vscode-laravel-extra-intellisense/assets/75478661/dfd5395c-0512-4ae2-b4bd-3f2a5ca13e5e)

Same problem, keeps popping up with this notification.

**Comment by amir9480** [comment]
@serhumanos @cubitworx @Temepest74 @1weiho @branivreyes 
Hi everyone,
It's a new feature to shows an error popup when the Laravel Extra Intellisense fails to load your application data to provide autocomplete. you may disable it for the current session using the "Don't show again" button.

In your case, looks like the PHP command can not be found and you need to change configurations to work on your machine.
You can read more about configurations here:
https://github.com/amir9480/vscode-laravel-extra-intellisense#configuration

**Comment by meduzen** [comment]
For anyone coming here and using macOS (might apply to Linux, too):

- run `which php` to know your PHP path
- adapt that path and put it in the **PHP command setting** of the extension

So in my case, using Herd, `which php` gives:

```sh
/Users/username/Library/Application Support/Herd/bin//php
```

So in the extension setting, I use:

```
~/Library/Application\ Support/Herd/bin/php -r "{code}"
```

<details>
<summary>View adaptations</summary>

- use `~/` instead of `/Users/username`
- prefix spaces by `\`
- replace `//` by `/`
</details>

If you put it directly in your VSC settings.json, adaptations are different and give:

```json
"LaravelExtraIntellisense.phpCommand": "~/Library/Application\\ Support/Herd/bin/php -r \"{code}\""
```
