### ISSUE TITLE
Not updating the intellisense when file is updated 

### ISSUE THREAD

**Issue by tbhaxor** [amir9480/vscode-laravel-extra-intellisense#106]
I have noticed that when the code in route / views / models are updated, I need to reload the window to reload auto-completion, otherwise it doesn't show the new route / view names.

**Comment by amir9480** [comment]
Hi @tbhaxor 
There is a file watcher for every auto-complete item provider.
Could you please check it out given patterns work for you?

https://github.com/amir9480/vscode-laravel-extra-intellisense/blob/master/src/RouteProvider.ts#L20

You may check data is reloaded from the output tab and Laravel Extra Intellisense from dropdown.

**Comment by tbhaxor** [comment]
Hi, I am using it through WSL and tested that changing, renaming and deleting file is not working for me. Do you have any other way to test it?

**Comment by amir9480** [comment]
@tbhaxor 
I using WSL too. I opened my projects via the following extension and everything works fine.

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

Make sure you are not opening the alias directory inside Windows Explorer.
Try opening a WSL terminal, navigate to your project directory, and use `code .` command to open your directory.

**Comment by tbhaxor** [comment]
Strange, I tested on Linux and it is working but not through WSL. I will setup a project from scratch and test again.

**Comment by amir9480** [comment]
@tbhaxor 
I'm not sure but I guess you are opening files in Host OS (Windows). Your vscode opening a directory like this:
`\\wsl.localhost\Ubuntu\\home\yourusername\proejct`
Which is not the right way to develop a WSL project.

You should use remote development instead of using the WSL extension or using dev containers.

**Comment by tbhaxor** [comment]
It is working now accidently.
