### ISSUE TITLE
Title: Recurring Error in VSCode Laravel Extra Intellisense Extension

### ISSUE THREAD

**Issue by heyyoudev** [amir9480/vscode-laravel-extra-intellisense#107]
**Description:**
I recently started encountering a persistent error with this extension. This issue did not occur previously, and it appears frequently now, disrupting my workflow. Attached is a screenshot for reference.

**Environment:**
VSCode Version: 1.88.1
Laravel Extra Intellisense Extension Version: Last updated 2024-04-16, 08:44:11
Operating System: Ubuntu 20.04

![laravel-extra-intellisense-error](https://github.com/amir9480/vscode-laravel-extra-intellisense/assets/7956593/869af213-7e50-42a8-899d-3f2ddc526154)

**Comment by tomheadifen** [comment]
Same here, I noticed this happening yesterday.

**Comment by AMD-NICK** [comment]
+1

![screenshot_2024-04-16_17 27 06@2x](https://github.com/amir9480/vscode-laravel-extra-intellisense/assets/9200174/0be9d4ed-1557-410f-886b-02bbc94b487c)

**Comment by Franche020** [comment]
Same here

`PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/var/www/html/storage/logs" and it could not be created: Permission denied in /home/franche020/proyectos/proyect/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:200
Stack trace:`

**Comment by Cris123m** [comment]
Similar error
`2024-04-16 11:39:55.020 [info] Laravel Extra Intellisense command started: Application Models
2024-04-16 11:39:55.020 [info] Laravel Extra Intellisense command started: Auth Data
2024-04-16 11:39:56.308 [error] Laravel Extra Intellisense Error:
 Application Models

PHP Parse error:  Unclosed '(' in Command line code on line 1

2024-04-16 11:39:56.464 [error] Laravel Extra Intellisense Error:
 Auth Data`

**Comment by amir9480** [comment]
@heyyoudev @tomheadifen @AMD-NICK  @Franche020 @Cris123m
Hi everyone
It's a new feature to shows an error when the Laravel Extra Intellisense fails to load your application data to provide autocomplete. you may disable it for the current session using the "Don't show again" button.

In you case, look like you have defined a `App\Policies\ModelPolicy` somewhere in your code but this class is not defined.

**Comment by AMD-NICK** [comment]
@amir9480 Thank you. I comment one line in AuthServiceProvider and it fixed mentioned problem.

Maybe you can help with another problem that started after installing this plugin. I am currently doing a project after a previous developer with whom there is no communication. After installing the plugin, I get this error in the console once per minute:

![screenshot_2024-04-17_16 32 50@2x](https://github.com/amir9480/vscode-laravel-extra-intellisense/assets/9200174/29848897-574b-4323-b8ba-0cc13ad85b77)

This error appears now even after uninstalling the plugin. This function is 100% defined in only one place. On the dev server I executed docker compose pause workspace and the problem stopped. This made me think that cron is running a schedule task in artisan once a minute, but manually executing the command does not cause the error. I then reset all data in Redis and ran docker compose unpause workspace, the problem also stopped appearing. This suggests that some regular task was added to REDIS that was spamming errors to the console once a minute.

**Comment by tomheadifen** [comment]
@amir9480 thank you for your response. My error was slightly different so I re-read the docs and noticed that this was happening because the base path was set incorrectly.

**Comment by heyyoudev** [comment]
Thank you, @amir9480  for the prompt response. You nailed the cause. Closing this issue...

**Comment by amir9480** [comment]
@AMD-NICK 
You should define every PHP function wrapped inside a `function_exists` if statement.

```php
if (! function_exists('json_success')) {
    function json_success(...)
    {
        // ...
    }
}
```

**Comment by tonoslav** [comment]
found it in my AuthServiceProvider.php
it was there by default I think 
Just comment it out and it should work
