### ISSUE TITLE
Constant mistakes

### ISSUE THREAD

**Issue by kosh2323** [amir9480/vscode-laravel-extra-intellisense#114]
When I open any project, I get constant errors, tell me what to do?
![scr1](https://github.com/amir9480/vscode-laravel-extra-intellisense/assets/82117170/20390626-73c4-4e7b-8653-b62fe396e285)

**Comment by mdjaman** [comment]
Same

**Comment by kosh2323** [comment]
The developers don't care about us, even if they wrote a word....

**Comment by amir9480** [comment]
@kosh2323 
Did you change the default language on your system
I can't read the logs!

**Comment by kosh2323** [comment]
I just deleted this extension and don't want to use it in the future. I'm tired of looking for solutions to problems.
