### ISSUE TITLE
Remove error notifications

### ISSUE THREAD

**Issue by eugabrielsilva** [amir9480/vscode-laravel-extra-intellisense#115]
Please remove these error notifications, they are really annoying.
Already tried the VSCode setting "disable Laravel Extra Intellisense notifications", but it doesn't work, they keep appearing.

![image](https://github.com/amir9480/vscode-laravel-extra-intellisense/assets/64693687/461907a1-7135-409f-a5b3-96bf5b255e57)

**Comment by kosh2323** [comment]
Yes, I get the same thing, unfortunately the developer is not responding.

**Comment by friday-deployer** [comment]
also please don't log errors to laravel error log. it mess up the log

**Comment by bensaufley** [comment]
For me, at least, this appears to consistently be the following error:

```
[error] Laravel Extra Intellisense Error:
 Custom Blade Directives

PHP Fatal error:  Uncaught InvalidArgumentException: Please provide a valid cache path. /path/to/project/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67
```

I'm on Laravel 10.4 but I even upgraded to 11.7 and still see the error. I agree it would be good to resolve this issue. It's not just an annoying pop-up, it's obviously a sign that something is broken.

**Comment by amir9480** [comment]
@eugabrielsilva @kosh2323 @friday-deployer @bensaufley 
This is a feature to inform you that autocomplete not working on your project,
You may either use "Don't show again" to disable the session or
update to **v0.6.6** and set the `LaravelExtraIntellisense.disableErrorAlert` setting to `true`.

Happy coding guys

**Comment by bensaufley** [comment]
> This is a feature to inform you that autocomplete not working on your project

OK thanks, but why not? Is it fixable? If so, how? I know the original issue here is "remove error notification" but I'd rather, like, resolve it than just hide/remove it.

**Comment by kosh2323** [comment]
Is it necessary to click "Hide notification" every time? This is not a solution. It's annoying, I chose to delete this extension.

**Comment by amir9480** [comment]
@bensaufley 
You should check the logs and traces to see why extension can not get data from your project.
Extension runs PHP codes to get data from your app.
Currently, I working on a project using Laravel 10 and everything loads fine on it but if your found a bug fill free to open PR to fix it.

**Comment by amir9480** [comment]
@kosh2323 New version has option to completely turn it off

**Comment by kosh2323** [comment]
> @kosh2323 New version has option to completely turn it off

Thanks for the answer, but there was a time when I used the extension, and that time has passed, I need a lot of distractions to solve problems, I don’t want to waste time. Maybe someday I'll return to using it. Good luck.
