### ISSUE TITLE
Validator safe() method shows as undefined

### ISSUE THREAD

**Issue by kirkkhua** [amir9480/vscode-laravel-extra-intellisense#118]
![Screenshot 2024-06-13 at 14 13 54](https://github.com/amir9480/vscode-laravel-extra-intellisense/assets/5412712/1cc029cf-8e65-41b3-8793-dae01b074f43)

Documentation: https://laravel.com/docs/10.x/validation#working-with-validated-input

**Comment by amir9480** [comment]
Hi @kirkkhua 
Laravel Extra Intellisense doesn't do anything related to PHP language. You should use an extension like 
https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
