### ISSUE TITLE
Is this meant to run along side other Intellisense Intelliphense plugins?

### ISSUE THREAD

**Issue by fbc** [amir9480/vscode-laravel-extra-intellisense#17]
Is this meant to run along side other Intellisense Intelliphense plugins?
Should I be disabling the others?

**Comment by amir9480** [comment]
Hello @fbc 
Thanks for using Laravel Extra Intellisense.

Yes, and you should use other plugins for PHP autocomplete.
Laravel Extra Intellisense just providing autocomplete for string parameters of Laravel functions like `route`, `view` and etc.
