### ISSUE TITLE
No autocomplete appearing with the extension

### ISSUE THREAD

**Issue by starcraft04** [amir9480/vscode-laravel-extra-intellisense#18]
I am using vscode 1.45.0 and the following extensions:
- laravel blade snippets
- laravel goto view
- laravel goto controller
- laravel snippets
- laravel blade
- php intelephense

I tried to install laravel extra intellisense. I relaunched vscode and if I try in a blade to enter {{ config('app. ') }} I don't get any proposition, same for return view in a controller.

It seems as if the application is not activated even though it is enabled...

**Comment by amir9480** [comment]
I need more information to find out why autocompletion not working on your machine.

Go to `Terminal > New Terminal` and Enter `php artisan route:list` and make sure you get the route list of your web app.

If you are getting desired output Then do the following instruction:
Disable All extensions except `Laravel Extra Intellisense`
Go to `Help > Developer Tools` and `Console` Tab.
If you see any errors send a screenshot of the error.

This is an issue from another extension but I explained how you can do that step by step.
https://github.com/amir9480/vscode-cpp-helper/issues/1#issuecomment-603793422

**Comment by starcraft04** [comment]
Hi,

php artisan route:list does well give me the expected output.

From the console I get:

[Extension Host] rejected promise not handled within 1 second: PHP Fatal error:  Class VscodeLaravelExtraIntellisenseProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Support\ServiceProvider::register) in Command line code on line 1

ERR PHP Fatal error:  Class VscodeLaravelExtraIntellisenseProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Support\ServiceProvider::register) in Command line code on line 1

[Extension Host] rejected promise not handled within 1 second: PHP Fatal error:  Class VscodeLaravelExtraIntellisenseProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Support\ServiceProvider::register) in Command line code on line 1

**Comment by amir9480** [comment]
@starcraft04 

Hello

What is your Laravel version?

**Comment by starcraft04** [comment]
5.2

**Comment by amir9480** [comment]
@starcraft04 

That is very old.
I highly recommend updating your Laravel version.

Look like this happening because of `register` was abstract in Laravel 5.2 and Laravel Extra Intellisense has a ServiceProvider that doesn't contain this method.

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/ServiceProvider.php#L54

I gonna add this as soon as I can.

**Comment by starcraft04** [comment]
thank you and yes, I should upgrade my laravel...
