### ISSUE TITLE
can, cant

### ISSUE THREAD

**Issue by adam-aido** [amir9480/vscode-laravel-extra-intellisense#19]
I guess theres is missing rule for methods can and cant.
With this code in a controller:
```php
$user = Auth::user();
$user->can('sth');
$user->cant('sth');
```
intelephense will throw error _Undefined method_.

**Comment by amir9480** [comment]
Hello.

for Facades, you should use:
https://github.com/barryvdh/laravel-debugbar

Laravel Extra Intellisense is only for providing string parts of codes.
I gonna check for the string part of `can`,`cant` to see its possible to implement or not as soon as I can.
