### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [amir9480/vscode-laravel-extra-intellisense#20]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _Laravel Extra Intellisense_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by amir9480** [comment]
Hello.

Can you publish this extension on open-vsx from .vsix files?

**Comment by orblazer** [comment]
I have no try that but i think its possible

**Comment by amir9480** [comment]
Ok.

You are allowed to publish this extension on open-vsx.
You can download .vsix file from https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.laravel-extra-intellisense .

**Comment by treyssatvincent** [comment]
I have published the 4.0.0 at : https://open-vsx.org/extension/amiralizadeh9480/laravel-extra-intellisense

@amir9480 the namespace `amiralizadeh9480` is public which means that everyone can publish new versions and other extensions under this namespace.

You can claim it if you want to.
You can also allow me to claim it and I'll try to keep `laravel-extra-intellisense` updated there.

**Comment by amir9480** [comment]
@treyssatvincent

It's awesome.
Thank you
