### ISSUE TITLE
How to autocomplete / also other than using . ?

### ISSUE THREAD

**Issue by benyaminl** [amir9480/vscode-laravel-extra-intellisense#22]
Hello, is it possible to do autocomplete on "/" char other than "." only? Thank you

**Comment by amir9480** [comment]
@benyaminl 
Hello

Sorry, I don't understand your issue

**Comment by benyaminl** [comment]
> 
> 
> @benyaminl
> Hello
> 
> Sorry, I don't understand your issue
> Please describe with details

Oh Sorry, Example like this 

we use view() helper function, and your autocomplete work on the string that's supplied to the view() helper, it only support using dot/"." character, which I think it should also autocomplete using "/" character, eg 
![image](https://user-images.githubusercontent.com/2817332/87872883-a9674580-c9e6-11ea-99fa-85cf59aa537e.png)

But none with "/"
![image](https://user-images.githubusercontent.com/2817332/87872890-b71ccb00-c9e6-11ea-919a-56f6a74622b3.png)

Maybe if it's possible, it also being part of the autocomplete :) Sorry for late reply, thank you for spare sometimes to respond to this(not clear) issue

**Comment by amir9480** [comment]
Please update to version 0.3.2 there is new config to this.

Use this to change `.` to `/`.

```json
"LaravelExtraIntellisense.viewDirectorySeperator": "/"
```
