### ISSUE TITLE
Open VSX Registry

### ISSUE THREAD

**Issue by kevariable** [amir9480/vscode-laravel-extra-intellisense#24]
Can you make it for VSCodium with VSX marketplace?. Thank you

**Comment by amir9480** [comment]
Hello,

I discussed this here: https://github.com/amir9480/vscode-laravel-extra-intellisense/issues/20
If the extension is not available yet, You are allowed to publish it.

**Comment by kevariable** [comment]
Yes, it's work. Manual way
