### ISSUE TITLE
Validation rules autocompletion does not work since v0.2.6

### ISSUE THREAD

**Issue by damiengrandi** [amir9480/vscode-laravel-extra-intellisense#25]
Validation rules inside controller methods aren't completed anymore.
![image](https://user-images.githubusercontent.com/7514487/90864371-d2397c80-e390-11ea-9d43-0f44835ec7c3.png)

It works fine if I rollback to v0.2.6:
![image](https://user-images.githubusercontent.com/7514487/90864474-0876fc00-e391-11ea-9d12-e1f36d59bf81.png)

**Comment by damiengrandi** [comment]
I forgot to precise I am using Laravel 7.

**Comment by damiengrandi** [comment]
I also tried to disable all other extensions, it didn't change anything.

**Comment by amir9480** [comment]
Hello

Look like this is an issue with parentheses and regex I used.
If you use this
```php
request()->validate([...])
```
Or
```php
$this->validate($request, [...])
```
Should work.

Gonna fix this bug as soon as I can.

**Comment by damiengrandi** [comment]
Hello, I confirm, it works with :
```php
$this->validate($request, [ 'lol' => '' ]) 
$request->validate([ 'lol' => '' ])
request()->validate([ 'lol' => '' ])
```
But not with :
```php
$this->validate(request(), [ 'lol' => '' ])
```
  
  
Also, in case some people don't use auto-closing parentheses or brackets, it does not work without the ending parenthesis ` ) `.
This won't autocomplete :
```php
$this->validate($request, [ 'lol' => ''
```
Nor this :
```php
$this->validate($request, [ 'lol' => '' ]
```
Not sure if it's relevant to fix this one though.. But I thought it was important to precise.

**Comment by amir9480** [comment]
@damiengrandi 

Please update to version 0.3.3.
If this issue still exists let me know.
