### ISSUE TITLE
The extension makes vs code slowly

### ISSUE THREAD

**Issue by khuccui2002** [amir9480/vscode-laravel-extra-intellisense#27]
I'm using VS code latest version (Version: 1.49.0) and this extension makes vs code slowly when I'm editing a php file >10.000 lines of codes. 
The extension host always took 100% of CPU, I tried to disable all extensions and enable again one by one and I found this extension is reason make VS code slow.
Please check.
Thanks.

**Comment by amir9480** [comment]
Hey @khuccui2002 

First, It's not best practice to put 10,000 LOC in one file
I Highly recommend you to not put all your code in just one file.

Second, Update to 0.3.3.

Also check: #28
