### ISSUE TITLE
Autocomplete is not working since last update

### ISSUE THREAD

**Issue by vitorvasc** [amir9480/vscode-laravel-extra-intellisense#28]
I just noticed that this extension is breaking the autocomplete since the last update, especially when I try to use it in a blade file.

![image](https://user-images.githubusercontent.com/12118857/93503325-431b7800-f8ee-11ea-8055-a85a2e61ad5c.png)

**Comment by RyanNutt** [comment]
I'm seeing the same thing, or at least something very similar. 

When this extension is enabled intellisense does not appear to work. The editor doesn't pull variable names as I start typing and no menu comes up after -> or ::  . Pressing Ctrl-Space only pops up a loading menu like the screen shot from OP. 

Also noticed with this active that formatters have issues. If I have format on save active a dialog pops up telling me that the formatter is running. The dialog never goes away, but canceling it will complete the save. And that's not only happening on PHP files. Also seeing it on JS files, still within a Laravel project.

Disabled this extension and everything appears to be back to normal.

**Comment by amir9480** [comment]
@vitorvasc @RyanNutt 
Hello

This issue is for regex I used to detect function/class name.
https://github.com/amir9480/vscode-laravel-extra-intellisense/blob/master/src/helpers.ts#L177

Still couldn't make a more optimized regex

For now I recommend use older version
![image](https://user-images.githubusercontent.com/16279288/93706620-350f6680-fb3d-11ea-8603-afa8046387e1.png)

**Comment by vitorvasc** [comment]
Thanks for the answer! 0.2.6 works fine here. 

Can't even describe how this extension increases my productivity, couldn't find any other like this.

**Comment by RyanNutt** [comment]
Is this something slated to be fixed in a future version, or is the solution just to stay with the old version?

**Comment by amir9480** [comment]
@RyanNutt 
I fix this as soon as I can
I need to optimize the regex I used, to prevent too many iteration.
Any contribution to optimizing regex to detect functions/classes appreciated.

**Comment by RyanNutt** [comment]
Really appreciate it. I didn't realize how much I missed having the views populate automatically until I disabled this extension yesterday.

**Comment by amir9480** [comment]
@vitorvasc @RyanNutt 

I changed regex and releaesd new version.
Please update to version 0.3.3 and if still this issue exists let me know

**Comment by RyanNutt** [comment]
Appears to be working. Thanks so much.

**Comment by SilNex** [comment]
localhost works, but still not working on ssh.

**Comment by RyanAidilPratama** [comment]
I have another issue here. After I updated my extension to version 0.3.3, I can't see the autocompletion for translation, but it working fine with routes, views, config, etc.
![image](https://user-images.githubusercontent.com/43450710/94154016-07654d00-feb0-11ea-8dd8-27fd6cc331ef.png)

**Comment by reduardo7** [comment]
Is related with #29

**Comment by amir9480** [comment]
@SilNex 
The extension does not support SSH

**Comment by amir9480** [comment]
@RyanAidilPratama 
Please send me a code sample that the IntelliSense not working with it

**Comment by RyanAidilPratama** [comment]
> 
> 
> @RyanAidilPratama
> Please send me a code sample that the IntelliSense not working with it

This happens in all of my laravel projects. But only auto completion for translations doesn't work.

**Comment by RyanNutt** [comment]
> And I don't want to jynx myself

Spoke too soon. It's still happening. The dialog pops up telling me that a formatter is running when I save a file. And it's not specific to blade or PHP files. Happens in Java files as well. But I haven't seen it happen when this extension is disabled.

**Comment by amir9480** [comment]
@vitorvasc @RyanNutt @reduardo7 @RyanAidilPratama 
Please update to version 0.3.4 and if still issue exists let me know.

I need help to make an optimized regex to detect class/function.
https://github.com/amir9480/vscode-laravel-extra-intellisense/blob/master/src/helpers.ts#L177

contributions are welcome.

**Comment by reduardo7** [comment]
> @vitorvasc @RyanNutt @reduardo7 @RyanAidilPratama
> Please update to version 0.3.4 and if still issue exists let me know.
> 
> I need help to make an optimized regex to detect class/function.
> https://github.com/amir9480/vscode-laravel-extra-intellisense/blob/master/src/helpers.ts#L177
> 
> contributions are welcome.

Thank you @amir9480 ! This seems to be working well now.

**Comment by RyanNutt** [comment]
Been coding for the last hour or so and haven't seen any issues.

**Comment by vitorvasc** [comment]
Updated on September 27 and it's still working, didn't find any problem. 

Apparently this issue is fixed, @amir9480 

Thank you so much.
