### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by samir-araujo** [amir9480/vscode-laravel-extra-intellisense#29]
Hi!

My VS Code asked to open this issue with the following information due to high CPU consumption

- Issue Type: `Performance`
- Extension Name: `laravel-extra-intellisense`
- Extension Version: `0.3.3`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.50.0-insider`

[amiralizadeh9480.laravel-extra-intellisense-unresponsive.cpuprofile.txt](https://github.com/amir9480/vscode-laravel-extra-intellisense/files/5275883/amiralizadeh9480.laravel-extra-intellisense-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by reduardo7** [comment]
The only way to make it works is disabling it.

**Comment by amir9480** [comment]
@samir-araujo @reduardo7

Hello
 
This is for new regex I used to detect class and function
Please send me a code sample that the intellisense not working with it.

**Comment by Simon-BEE** [comment]
Same here, I'm working on Debian 10, temporary solution is to downgrade in 0.3.2 (previous version).
Thanks for your work @amir9480 , one of best vscode extension for Laravel ecosystem !

**Comment by amir9480** [comment]
@Simon-BEE @samir-araujo @reduardo7 

Please update to version 0.3.4 and if still issue exists let me know.
