### ISSUE TITLE
Not working in Mac OS Catalina

### ISSUE THREAD

**Issue by weidmaster** [amir9480/vscode-laravel-extra-intellisense#32]
I wanted to try this extension because I work a lot with Laravel too but unfortunately it is not working in my environment at all. I am using Mac OS and I type the examples but no intellisense is showing. I don't know how to debug and send you some info, but I wanted to help reporting the issue.

It seems lots of extensions for Laravel does not work with Mac OS. I don't know why.

**Comment by amir9480** [comment]
Hi @weidmaster 

First, Make sure your laravel application has no errors and the artisan command working fine.
For example check `php artisan route:list` works fine.

You can check logs as I explained here for another extension.
https://github.com/amir9480/vscode-cpp-helper/issues/1#issuecomment-603793422

**Comment by weidmaster** [comment]
> Hi @weidmaster
> 
> First, Make sure your laravel application has no errors and the artisan command working fine.
> For example check `php artisan route:list` works fine.
> 
> You can check logs as I explained here for another extension.
> [amir9480/vscode-cpp-helper#1 (comment)](https://github.com/amir9480/vscode-cpp-helper/issues/1#issuecomment-603793422)

Hello! Yes my Laravel application is working and ```route:list``` is showing everything. No log errors for Laravel.

I followed the instructions from the other extension to debug. I couldn't save the log file because right clicking the logs does not work either but I got the full output here. Yes everything is disabled and only this extension was enabled at the moment.

<img width="874" alt="Captura de Tela 2020-10-23 às 14 21 45" src="https://user-images.githubusercontent.com/9614642/97034611-8f845400-153b-11eb-8898-29723c42ec85.png">


Thanks in advance and I hope we can make this work. Maybe some Linux specifics would work? We can try as well.

**Comment by amir9480** [comment]
@weidmaster 
This log is not an error so I still can not guess what the problem is.
I also have no access to mac os.

Here are some questions that might help me find the issue:

Which Laravel version do you use?
Which PHP version you are using and are you accessing it with `php` in the terminal or something else?
Are you opening your laravel project root directory in vscode? I mean is the vendor/artisan in the root?
Did you try the fresh installation of laravel?

**Comment by weidmaster** [comment]
@amir9480 Hello, I figured out the issue! It is not the OS, it is the folder structure of my project not following the default Laravel structure! As follows:

- I have the Laravel app inside /projects and /assets is separated and there is no /public folder

![Captura de Tela 2020-10-27 às 10 34 40](https://user-images.githubusercontent.com/9614642/97310246-c0b59a80-1841-11eb-8ad4-8626095fd9f8.png)

I did test the extension in my other project with Voyager and it does work! I am glad I could trace the issue back to the project structure. So I think the extension only needs an option to define the Laravel project folder, as it seems to load the resources from there.

Thanks for your patience.

**Comment by amir9480** [comment]
@weidmaster 
Please update to version 0.4.0 to access docker support.
https://github.com/amir9480/vscode-laravel-extra-intellisense#sample-config-to-use-docker

Also, there is a new configuration to set the application root path
https://github.com/amir9480/vscode-laravel-extra-intellisense#sample-config-to-use-docker

**Comment by weidmaster** [comment]
@amir9480 Thank you very much for the update and the new config options. It works now with your examples.
