### ISSUE TITLE
Not getting any suggestions.

### ISSUE THREAD

**Issue by cAstraea** [amir9480/vscode-laravel-extra-intellisense#37]
Hello. If anyone can help me pinpoint down what's wrong would greatly appreciate it. ^^

I tried disabling all extensions and only turning on the Laravel Extra Intellisense 0.4.1 since I thought there might be a conflict but didn't work.  Not getting any intelisense suggestions for routes , views , etc. 
I'm using docker containers and this is my settings.json for the extension
```
   "LaravelExtraIntellisense.phpCommand": "docker exec -w /var/www/html -u laravel php php -r \"{code}\"",
    "intelephense.files.maxSize": 3000000,
    "LaravelExtraIntellisense.basePathForCode": "/var/www/html",
    "LaravelExtraIntellisense.basePath": "/var/www/html"
```

This is my list of recommended extensions for current workspace. 
```
	"recommendations": [
        "formulahendry.auto-close-tag",
        "coenraads.bracket-pair-colorizer",
        "mikestead.dotenv",
        "vincaslt.highlight-matching-tag",
        "xabikos.javascriptsnippets",
        "onecentlin.laravel-blade",
        "austenc.laravel-blade-spacer",
        "dacoto.laravel-easy-blade-snippets",
        "dacoto.laravel-easy-blade-snippets",
        "amiralizadeh9480.laravel-extra-intellisense",
        "codingyu.laravel-goto-view",
        "pkief.material-icon-theme",
        "leizongmin.node-module-intellisense",
        "christian-kohler.npm-intellisense",
        "christian-kohler.path-intellisense",
        "bmewburn.vscode-intelephense-client",
        "marabesi.php-import-checker",
        "mehedidracula.php-namespace-resolver",
        "kokororin.vscode-phpfmt",
        "greven.umbra",
        "visualstudioexptteam.vscodeintellicode"
	],
```

**Comment by amir9480** [comment]
@cAstraea Hi

Make sure your command is working.
```
docker exec -w /var/www/html -u laravel php php -r \"{code}\"
```

You can see errors in the developer console.
`Help > Toggle Developer Tools > Console`

**Comment by cAstraea** [comment]
How to check that ? :) This is  what happens don't see any error though. Maybe I'm missing a setting somewhere ? 

https://user-images.githubusercontent.com/13070662/106130749-6c84c400-616a-11eb-91e7-2c74787e1b67.mp4

**Comment by amir9480** [comment]
@cAstraea 
Have you opened your project root directory with vscode?
Reload vscode to run fetching codes.
If you still don't see any errors run your command manually to see if it gives any output or not.
You can get codes here:
https://github.com/amir9480/vscode-laravel-extra-intellisense/blob/master/src/helpers.ts#L69

**Comment by cAstraea** [comment]
Ahhh right makes sense now :sob: My root was actually in the src but was opening the parent folder :man_facepalming:  Thanks a lot ! Think will need to reorganize my folder structure a bit.

**Comment by tynguyen2k1** [comment]
> Ahhh right makes sense now  My root was actually in the src but was opening the parent folder  Thanks a lot ! Think will need to reorganize my folder structure a bit.

I have the same problem as you, how do you fix it?
