### ISSUE TITLE
Development Guide for contribution

### ISSUE THREAD

**Issue by Wulfheart** [amir9480/vscode-laravel-extra-intellisense#38]
I’d like to contribute some features but I am unsure what is the best way to setup my VSCode for local development. Any instructions?

**Comment by amir9480** [comment]
@Wulfheart 
Hi there,

Just clone the repository.
Install development dependencies using npm. (`npm i`)
Open the project folder in vscode
Run `npm run watch` command and press `F5` to launch the development environment.
