### ISSUE TITLE
Route autocomplete does not respect name()

### ISSUE THREAD

**Issue by lefrancois** [amir9480/vscode-laravel-extra-intellisense#41]
Route group prefixes like `Route::name('frontend.')->group(function() {` will not be shown in autocompletion.

**Comment by amir9480** [comment]
@lefrancois 
Hi

Extension gets route names from your application.
Check your routes with:
```
php artisan route:list
```

**Comment by lefrancois** [comment]
@amir9480 
You are right, had to restart vsCode, but now it looks good. 👍🏼
