### ISSUE TITLE
Explain or document why the extension attempts to run PHP/Laravel every 1 minute

### ISSUE THREAD

**Issue by neilwhitespace** [amir9480/vscode-laravel-extra-intellisense#42]
Hi there,

My laravel.log is showing an exception for the absence of Memcached and a syntax issue relating to PHP 7.3.

I've just been through many hours of debugging on a Laravel 8 app and done the following:

- Cycled Telescope installation.
- Installed DebugBar (which had no insights).
- Completely removed homebrew, deleting hundreds of binaries, many of which need to be reinstalled.
- Re-configured my PHP stack three or four times in various unrecoverable ways.
- Re-configured MAMP in various ways.

After much hair pulling, I have finally realised it is this extension running laravel/cli every minute on the console, using what seems to be configured as the default Mac OS PHP (7.3, without Memcached). 

I have realised this on my own, after debugging almost everything to do with my known stack. I did not for a moment think it would be the fault of an extension which provides autocomplete and syntax help in my IDE!

Can you _**please**_ write some notes within either the readme or make it incredibly obvious within the extension that it is polling the Laravel CLI every 1 minute?

Please can you also explain what the reason for this is, as it is likely that others will want to know why their app is being executed without their knowledge.

This is otherwise a great extension and I enjoy using it, but this one niggle has had me wondering whether I was going mad for far too long. Anything you can do to alleviate this would be very much appreciated! 👍

**Comment by amir9480** [comment]
Hi @neilwhitespace 

Sorry for wasting your time
My extension supposed to save people time not waste it :)

The extension needs to get information from your Laravel application and this happens using this command.
```
php -r "codes"
```
and parses the result.
For example, getting routes, views, configs, middleware, and ...

You can change this command to your custom command using [this setting](https://github.com/amir9480/vscode-laravel-extra-intellisense#laravelextraintellisensephpcommand).
