### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by therafirends** [amir9480/vscode-laravel-extra-intellisense#43]
- Issue Type: `Bug`
- Extension Name: `laravel-extra-intellisense`
- Extension Version: `0.5.2`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.54.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by amir9480** [comment]
Duplicate #33
