### ISSUE TITLE
Feature Request: Blade Directive Autocompletions

### ISSUE THREAD

**Issue by mikebronner** [amir9480/vscode-laravel-extra-intellisense#45]
Would love to see blade template auto-completions based on actual registered blade templates (as opposed to a static library). This would automatically take in any blade macros and laravel packages that bring in their own blade directives. :)

Awesome package, it's at the core of my VSCode setup! :)

**Comment by amir9480** [comment]
@mikebronner 
This feature is now available at version 0.6.0.
