### ISSUE TITLE
Feature Request: Add Toggle for snake_case vs camelCase.

### ISSUE THREAD

**Issue by mikebronner** [amir9480/vscode-laravel-extra-intellisense#46]
Hi @amir9480,

Would you consider adding a toggle in settings to autocomplete model attributes using camel case, instead of snake case?
PSRs dictate that class properties be in camelCase, and in our company style-guide we currently consider model attributes properties, rather than database fields.

Thanks :)
~Mike Bronner

**Comment by amir9480** [comment]
@mikebronner 
Hi

Please update to version 0.6.0 and change your vscode settings like this:
```json
"LaravelExtraIntellisense.modelAttributeCase": "camel",
"LaravelExtraIntellisense.modelAccessorCase": "camel"
```

If there is any bug, please let me know.
