### ISSUE TITLE
"LaravelExtraIntellisense.basePath" does not work if relative to VSCode workspace folder

### ISSUE THREAD

**Issue by Sazeidya** [amir9480/vscode-laravel-extra-intellisense#70]
Hello,

I have problems setting the base path for my laravel application. The application is not in the root of the vscode project folder, but inside a subfolder "application". When I try to set the "LaravelExtraIntellisense.basePath" to something like "./application", "/application" or "application" it does not work. 

But setting it from the root of the system does work though. Unfortunately, this way the workspace settings file cannot be committed because the folder is different per user. Is there a way to set the basePath relative to the VSCode workspace folder?

**Comment by y-web21** [comment]
I have the same problem, but I have another solution.

This is the directory structure of my project.

```shell
$ tree -L 2 -d
.
├── app
│   ├── application  # nested laravel root
│   ├── bootstrap
│   ├── config
│   ├── database
│   ├── lang
│   ├── node_modules
│   ├── public
│   ├── resources
│   ├── routes
│   ├── storage
│   ├── tests
│   └── vendor
└── docker
     ├── mysql
     ├── nginx
     └── php
```

I created a code-workspace based on the [Sample config to use docker](https://github.com/amir9480/vscode-laravel-extra-intellisense#sample-config-to-use-docker). Maybe it's because I use bind mounts, but anyway this didn't work for me.

```js
{
    "folders": [
        {
            "path": "."
        },
    ],
    "settings": {
    	// doesn't work
        "LaravelExtraIntellisense.phpCommand": "docker exec -w /var/www/app -u 1000 laravel php -r \"{code}\"",
        "LaravelExtraIntellisense.basePathForCode": "/var/www/html"  // bind mount ./app/application
    }
}

```

The extension works at least when Laravel is in the project root. So I edited code-workspace to make it multi-root.

```js
{
    "folders": [
        {
            // my laravel root
            "path": "./application"
        },
        {
            "path": "."
        }
    ],
    "settings": {
    }
}
```

Now it works properly.

**Comment by amir9480** [comment]
@Sazeidya relative path is now available and you need to set your setting to:
```json
"LaravelExtraIntellisense.basePath": "./application" 
```

If you are using docker, you need to do this with docker volumes, there is no way to resolve relative paths inside the virtual machine.

**Comment by Sazeidya** [comment]
Thank you very much! :) Have a nice week!
