### ISSUE TITLE
Doesn't seem to work with @for loops

### ISSUE THREAD

**Issue by threed-factory-store** [amir9480/vscode-laravel-extra-intellisense#72]
If I have a @for loop inside a div, this extension will mark the outermost closing div inside the @for loop as being the match for the outer div.

![Screenshot from 2022-07-19 11-00-33](https://user-images.githubusercontent.com/79147271/179782948-cd679b62-e35d-45d6-9b90-da211f6d2083.png)

**Comment by amir9480** [comment]
@threed-factory-store Laravel Extra Intellisense doesn't provide any highlighting, please use proper extensions like https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade
