### ISSUE TITLE
Feature request: Improve pest intellisense

### ISSUE THREAD

**Issue by alexviar** [amir9480/vscode-laravel-extra-intellisense#74]
![image](https://user-images.githubusercontent.com/10967713/182695679-c4d4ec29-1842-4787-aee7-aee839375cac.png)

Hi.

Is posible infer type of `$this`? Currently we have to add the comment `/** @var TestCase $this  */` but it does not detect all methods of `TestCase`

Thanks you.

**Comment by amir9480** [comment]
Hi @alexviar 
Laravel Extra Intellisense doesn't provide autocomplete for php codes, you should use proper extensions like https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
