### ISSUE TITLE
Extension doesnt work when not in default root folder.

### ISSUE THREAD

**Issue by RidoneMuh** [amir9480/vscode-laravel-extra-intellisense#76]
Please help anyone,

I cant use this extension when my Laravel Project isn't in root folder, in my case in code folder. How can I use the Base path for my case ? 

This is my folder structure...
![image](https://user-images.githubusercontent.com/49577805/189168643-e26c2834-609d-4467-9d52-c1caf24adc50.png)

**Comment by amir9480** [comment]
@RidoneMuh 
I think you should use the base path configuration like this:

```json
"LaravelExtraIntellisense.basePath": "/yourproject/code",
```

There is also a sample configuration for docker (Laradock in my case) please [check it out](https://github.com/amir9480/vscode-laravel-extra-intellisense#sample-config-to-use-docker).

**Comment by scofield-ua** [comment]
I've used a different command for `LaravelExtraIntellisense.basePath`:

```
docker exec $(docker ps --filter name=-app --format '{{.ID}}') php -r "{code}"
```

Command inside `$()` will [filter](https://docs.docker.com/engine/reference/commandline/ps/) by name `-app` and output ID of the container.
