### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by imvikaskumar** [amir9480/vscode-laravel-extra-intellisense#77]
- Issue Type: `Bug`
- Extension Name: `laravel-extra-intellisense`
- Extension Version: `0.6.2`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Conflict409** [comment]
![image](https://user-images.githubusercontent.com/74853257/193739638-9e731e32-8b96-48ac-9a23-4bcbb37c110e.png)
