### ISSUE TITLE
Triggers Constant Laravel Errors

### ISSUE THREAD

**Issue by mikebronner** [amir9480/vscode-laravel-extra-intellisense#9]
It looks like this extension is making constant requests to the app through PHP. This is triggering a constant deluge of application errors, as the extension is not tenant-aware, and does not execute its requests through the necessary Laravel middleware that determines the active tenant.

I would not expect VSCode plugins to make PHP requests to my application in order to understand them, but rather to run their own internal language server (if necessary), and parse the files in the directories as needed, to get more information.

As this stands now, I am unable to use this plugin because of this issue.

**Comment by amir9480** [comment]
I get Laravel application information like all routes, views namespaces, translation namespaces, all configs using raw PHP codes.
So if there is some easier and better way to do these, please let me know.

For example, I using this code to get Laravel routes.
```php
define('LARAVEL_START', microtime(true));
require_once "vendor/autoload.php";
require_once "bootstrap/app.php";
$kernel = $app->make(Illuminate\\Contracts\\Http\\Kernel::class);
$response = $kernel->handle($request = Illuminate\\Http\\Request::capture());

echo json_encode(
array_map(
function ($route) {
return [
'method' => implode('|', array_filter($route->methods(), function ($method) {return $method != 'HEAD';})),
'uri' => $route->uri(),
'name' => $route->getName(),
'action' => str_replace('App\\\\Http\\\\Controllers\\\\', '', $route->getActionName()),
'parameters' => $route->parameterNames()
];
}, 
app('router')->getRoutes()->getRoutes()
)
);
```

 Should I provide some setting to load information manually using some status bar button instead of automatically call PHP codes on saving files?

**Comment by mikebronner** [comment]
Hi @amir9480, I think the core problem is that you are using the application itself to get the desired information. I understand that that approach provides an easy way to get the items from the CoI in Laravel, but that brings with it the problems that the middleware are not run.

Perhaps if you could run all middleware as well, it might not be an issue. Do you think that is doable?

**Comment by amir9480** [comment]
Hello.
Thanks for helping me to fix this issue and sorry for my bad English.
I used [Laravel's source](https://github.com/laravel/laravel/blob/master/public/index.php) to boot up Laravel and only removed this part of the code:
```php
$response->send();
$kernel->terminate($request, $response);
```
To prevent website home output and instead I used my own code to write output.
If you test that code I sent before, You can see all middlewares for the home route will run.
Do you think if I use [artisan](https://github.com/laravel/laravel/blob/master/artisan) code instead will fix this issue or not?

> Do you think that would be doable?
If it's possible to write One-File PHP code to do that and get desired information as JSON output, then I can use that code for my extension.
I would appreciate if you help me to do this.

**Comment by mikebronner** [comment]
@amir9480 I'm not sure. I guess another problem with multi-tenancy projects is that they are URL-aware, and perhaps because no URL is defined, that's why the plugin is not working for me. What URL do you use to make the request in your plugin?

**Comment by amir9480** [comment]
@mikebronner I do not use any special URL so Laravel will load home route (root route) (test.local/).
I guess this happens because route `/` in your application throws an exception (HttpNotFoundException).
I need to do some experiments to see if I can fix error using artisan code instead.

**Comment by mikebronner** [comment]
Sorry for taking so long to follow up. I'm not seeing any errors now. I will continue testing. :) Thanks!

**Comment by amir9480** [comment]
@jzpeepz 
Hello.
Which Laravel version exactly you use?
I using `FileLoader::namespaces()` to dectect translation namespaces for translation autocomplete.

**Comment by jzpeepz** [comment]
I have seen this happen in both Laravel 5.1 and 5.3 projects.

**Comment by amir9480** [comment]
@jzpeepz Sorry. That's too old.
But i gonna remove auto-retry after any error happens.

**Comment by jzpeepz** [comment]
@amir9480 That would be good enough. I don't really expect it to work in older projects, but it would be nice if it didn't fill up my logs with errors. :)

I appreciate how helpful and responsive you have been on this issue!

**Comment by amir9480** [comment]
@jzpeepz It's a good idea to disable logging when running application from the extension.
After some research around the web, I found a way to disable logger and hope it works in laravel 5.3.
```php
class VscodeLaravelExtraIntellisenseProvider extends \Illuminate\Support\ServiceProvider
{
    public function boot()
    {
        $this->app['log']->setHandlers([new \Monolog\Handler\NullHandler()]);
    }
}

$app->register(new VscodeLaravelExtraIntellisenseProvider($app));
```
